In [1]:
import platform
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc

c:\Users\boomd\Documents\ax_study\04_MACHINE_LEARNING\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = pd.read_csv('diabetes.csv')
# 데이터 추출 5개
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [4]:
df.shape

(768, 9)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [6]:
# 데이터 꼬리에서부터 N개 추출, 공백 시 5개
df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
df.iloc[100:200]
#원본 데이터인 df는 보존 해놓고 변수를 통해 작성한다.

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
100,1,163,72,0,0,39.0,1.222,33,1
101,1,151,60,0,0,26.1,0.179,22,0
102,0,125,96,0,0,22.5,0.262,21,0
103,1,81,72,18,40,26.6,0.283,24,0
104,2,85,65,0,0,39.6,0.930,27,0
...,...,...,...,...,...,...,...,...,...
195,5,158,84,41,210,39.4,0.395,29,1
196,1,105,58,0,0,24.3,0.187,21,0
197,3,107,62,13,48,22.9,0.678,23,1
198,4,109,64,44,99,34.8,0.905,26,1
199,4,148,60,27,318,30.9,0.150,29,1

In [8]:
df[['Pregnancies', 'Glucose', 'Insulin']].head(100)
 #여러 열의 데이터를 추출

    Pregnancies  Glucose  Insulin
0             6      148        0
1             1       85        0
2             8      183        0
3             1       89       94
4             0      137      168
..          ...      ...      ...
95            6      144      228
96            2       92        0
97            1       71       76
98            6       93       64
99            1      122      220

[100 rows x 3 columns]

In [9]:
df.sort_values(by='Pregnancies') #오름차순 정렬
#df.sort_values(by='Pregnancies', ascending=False) #내림차순 정렬

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
16,0,118,84,47,230,45.8,0.551,31,1
736,0,126,86,27,120,27.4,0.515,21,0
713,0,134,58,20,291,26.4,0.352,21,0
727,0,141,84,26,0,32.4,0.433,22,0
681,0,162,76,36,0,49.6,0.364,26,1
...,...,...,...,...,...,...,...,...,...
691,13,158,114,0,0,42.3,0.257,44,1
298,14,100,78,25,184,36.6,0.412,46,1
455,14,175,62,30,0,33.6,0.212,38,1
88,15,136,70,32,110,37.1,0.153,43,1
159,17,163,72,41,114,40.9,0.817,47,1

In [ ]:
# loc[ ] : 특정 조건에 해당하는 데이터를 추출 location
# 층별화 : 데이터를 특정 범주 항목의 특성에 따라 나누어 분석

# insulin >= 100인 명단 추출
cond1 = df['Insulin'] >= 100
df.loc[cond1]
cond2 = df['BloodPressure'] <=100
df.loc[cond1 & cond2] # 두 조건이 모두 만족되는 값들

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
4,0,137,40,35,168,43.1,2.288,33,1
8,2,197,70,45,543,30.5,0.158,53,1
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
16,0,118,84,47,230,45.8,0.551,31,1
...,...,...,...,...,...,...,...,...,...
748,3,187,70,22,200,36.4,0.408,36,1
753,0,181,88,44,510,43.3,0.222,26,1
755,1,128,88,39,110,36.5,1.057,37,1
763,10,101,76,48,180,32.9,0.171,63,0
765,5,121,72,23,112,26.2,0.245,30,0

In [16]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64